# Generated by Django 3.1.4 on 2024-06-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('sobrenome', models.TextField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.TextField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=10)),
                ('tipo_sanguineo', models.TextField(max_length=5)),
                ('telefone', models.TextField(max_length=20)),
                ('cpf', models.TextField(max_length=14)),
                ('rg', models.TextField(max_length=20)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('responsavel', models.TextField(max_length=255)),
            ],
        ),
    ]
