# Generated by Django 3.1.4 on 2024-06-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='rg',
            field=models.CharField(max_length=20),
        ),
    ]
