# Generated by Django 3.1.4 on 2024-06-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240629_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='tipo_sanguineo',
            field=models.TextField(choices=[('a+', 'A+'), ('a-', 'A-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-')], max_length=10),
        ),
    ]
