# Generated by Django 3.1.4 on 2024-07-01 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240630_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='cpf_responsavel',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='rg_responsavel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Nova_Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('data_consulta', models.DateField()),
                ('anamnese', models.TextField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('observacao', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cadastro')),
            ],
        ),
    ]
