# Generated by Django 3.1.4 on 2024-07-01 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240630_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='cpf_responsavel',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='rg_responsavel',
        ),
    ]
