# Generated by Django 3.1.4 on 2024-07-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240630_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='cpf_responsavel',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='rg_responsavel',
            field=models.CharField(default='', max_length=20),
        ),
    ]
