# Generated by Django 3.1.4 on 2024-07-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240630_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
