# Generated by Django 3.1.4 on 2024-07-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240630_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cpf_responsavel',
            field=models.CharField(blank=True, default='', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='responsavel',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='rg_responsavel',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='sexo',
            field=models.TextField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='telefone',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='tipo_sanguineo',
            field=models.TextField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-')], max_length=10, null=True),
        ),
    ]
