# Generated by Django 3.1.4 on 2024-07-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240630_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='sobrenome',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
