# Generated by Django 3.1.4 on 2024-07-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20240630_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='responsavel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-')], max_length=10, null=True),
        ),
    ]
